<a href="https://colab.research.google.com/github/Udaykiran06-art/NUMPY-METHODS/blob/main/Numpy_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Creating min()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print(values.min())


[[10 20 30]
 [40 50 60]]
10


In [ ]:
#Creating max()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print(values.max())

[[10 20 30]
 [40 50 60]]
60


In [ ]:
#Creating sum()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print(values.sum())

[[10 20 30]
 [40 50 60]]
210


In [ ]:
#Creating reshape()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print()
print(values.reshape(1,6))

[[10 20 30]
 [40 50 60]]

[[10 20 30 40 50 60]]


In [ ]:
#Creating reshape()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print()
print(values.reshape(3,2))

[[10 20 30]
 [40 50 60]]

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
#Creating reshape()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print()
print(values.reshape(6,1))

[[10 20 30]
 [40 50 60]]

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


In [ ]:
#Creating count_nonzero()method
import numpy as np
details = np.array([[10,20,30,0],[40,50,60,0]])
values = np.array(details)
print(values)
print(np.count_nonzero(values))

[[10 20 30  0]
 [40 50 60  0]]
6


In [ ]:
#Creating sort()method
import numpy as np
details = np.array([[55,45,12],[35,25,1]])
values = np.array(details)
print(values)
values.sort()
print()
print(values)

[[55 45 12]
 [35 25  1]]

[[12 45 55]
 [ 1 25 35]]


In [ ]:
#Creating flatten()method
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print(values.flatten())

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [ ]:
#Creating adding value to array of values
import numpy as np
details = np.array([[10,20,30],[40,50,60]])
values = np.array(details)
print(values)
print()
print(values+2)

[[10 20 30]
 [40 50 60]]

[[12 22 32]
 [42 52 62]]


In [ ]:
#Creating Diagonal matrix
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()
print(matrix.diagonal())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]


In [ ]:
#Creating the trace of a matrix
import numpy as np
matrxi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()
print(matrix.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

15


In [ ]:
#Creating the trace of a matrix
import numpy as np
matrxi = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()
print(sum(matrix.diagonal()))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

15


In [ ]:
#Creating adding and subtracting matrices
#Adding two matrices
import numpy as np
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.array([[1,1,2],[2,2,3],[3,3,4]])
print(matrix_a)
print()
print(matrix_b)
print()
print(np.add(matrix_a,matrix_b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2]
 [2 2 3]
 [3 3 4]]

[[ 2  3  5]
 [ 6  7  9]
 [10 11 13]]


In [ ]:
#Subtracting two matrices
import numpy as np
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.array([[1,1,2],[2,2,3],[3,3,4]])
print(matrix_a)
print()
print(matrix_b)
print()
print(np.subtract(matrix_a,matrix_b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2]
 [2 2 3]
 [3 3 4]]

[[0 1 1]
 [2 3 3]
 [4 5 5]]


In [ ]:
#Adding two matrices
import numpy as np
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.array([[1,1,2],[2,2,3],[3,3,4]])
print(matrix_a)
print()
print(matrix_b)
print()
print(matrix_a+matrix_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2]
 [2 2 3]
 [3 3 4]]

[[ 2  3  5]
 [ 6  7  9]
 [10 11 13]]


In [ ]:
#Subtracting two matrices
import numpy as np
matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.array([[1,1,2],[2,2,3],[3,3,4]])
print(matrix_a)
print()
print(matrix_b)
print()
print(matrix_a-matrix_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2]
 [2 2 3]
 [3 3 4]]

[[0 1 1]
 [2 3 3]
 [4 5 5]]
